include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_specify_types: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    directives_ordering: true
