name: flutter_boilerplate
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.4
  intl: ^0.18.1
  equatable: ^2.0.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/generated/assets/
  line_length: 80

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/colors/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
